dj_start/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', 'dj_start.views.home', name='home'),
    url(r'^contact/$', include('contact.urls'), name="contact"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^survey/', include('survey.urls', namespace='survey')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
)

survey/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.views import login

from survey import views

survey_patterns = patterns('',
    url(r'^$', views.SurveyView.as_view(), name='survey'),
    url(r'^/page/(?P<page>\d+)$', views.SurveyView.as_view(), name='survey'),
    url(r'^/result$', views.ResultView.as_view(), name='result'),
    url(r'^/closest_path$', views.ClosestPath.as_view(), name='closest')
)

urlpatterns = patterns('',
    url(r'^$', views.ListView.as_view(), name='list'),
    url(r'^(?P<survey_id>\d+)', include(survey_patterns)),
)

survey/models.py
import datetime

from django.db import models

from survey import managers


class Survey(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__()

    def shorten_description(self, length=160):
        max_length = length - 3
        if len(self.description) > length:  # 3 for the ellipses
            return self.description[:max_length] + '...'
        return self.description

    class Meta:
        ordering = ['-created_at']


class Page(models.Model):
    page_num = models.PositiveIntegerField()
    survey = models.ForeignKey(Survey)

    objects = managers.DefaultPageManager()

    def __unicode__(self):
        return "Pg {} from {}".format(self.page_num, self.survey)

    def __str__(self):
        return self.__unicode__()

    class Meta:
        unique_together = ('page_num', 'survey')


class Question(models.Model):
    SINGLE = 'radio'
    MULTIPLE = 'checkbox'
    TYPE_IN_CHOICES = (
        (SINGLE, 'Single answer'),
        (MULTIPLE, 'Multiple answers')
    )

    page = models.ForeignKey(Page)
    question_text = models.CharField(max_length=300)
    position = models.IntegerField(help_text="Question order")
    type = models.CharField(max_length=20, choices=TYPE_IN_CHOICES, default=MULTIPLE)

    def __unicode__(self):
        return self.question_text[:10]

    def __str__(self):
        return self.__unicode__()

    class Meta:
        ordering = ['position']


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    score = models.IntegerField()

    objects = managers.DefaultAnswerManager()

    def __unicode__(self):
        return self.answer_text[:10]

    def __str__(self):
        return self.__unicode__()


class Result(models.Model):
    survey = models.ForeignKey(Survey)
    summary = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    min_score = models.IntegerField()
    max_score = models.IntegerField()

    objects = managers.DefaultResultManager()

    def __unicode__(self):
        return self.summary[:10]

    def __str__(self):
        return self.__unicode__()

survey/views.py
import logging

from django.shortcuts import (render, HttpResponseRedirect,
                              Http404, get_object_or_404)
from django.core.urlresolvers import reverse
from django.views.generic.base import View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from survey.models import Survey, Question, Answer, Page, Result
from closealternative import compute_closest_alternatives, AnsTuple


logger = logging.getLogger(__name__)


class ListView(View):
    template_name = 'survey/list.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ListView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        """Display a list with all the surveys available.

        The results are paged.

        :param request:
        :return:
        """
        page = request.GET.get('page', 1)
        limit = 3

        all_surveys = Survey.objects.all()
        paginator = Paginator(all_surveys, limit)

        try:
            surveys = paginator.page(page)
        except PageNotAnInteger:
            surveys = paginator.page(1)
        except EmptyPage:
            surveys = paginator.page(paginator.num_pages)

        start_at = (surveys.number - 1) * limit + 1

        context = {
            'surveys': surveys,
            'start_at': start_at
        }

        return render(request, self.template_name, context)


class SurveyView(View):
    template_name = 'survey/survey.html'
    SURVEY_PAGE = 'survey_page'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(SurveyView, self).dispatch(request, *args, **kwargs)

    def get(self, request, survey_id, page=1):
        """Renders a specific survey page.

        Store in session the survey_page (current page) and the ids of the answers.
        The survey_page is used to restrict the user (skip ahead in the survey).
        The answer ids is used later to compute a close result alternative.

        :param request:
        :param survey_id: numeric
        :param page: numeric
        :return:
        """
        survey = get_object_or_404(Survey, pk=survey_id)
        page = int(page)
        session_page = request.session.get(self.SURVEY_PAGE, 1)

        if page != session_page:
            return HttpResponseRedirect(reverse('survey:survey', args=(survey_id, session_page)))

        if page == 1:
            request.session['answers'] = []

        questions = Question.objects.filter(page__page_num=page, page__survey=survey_id)
        next_page = Page.objects.get_next_page(survey_id, page)

        context = {
            'survey': survey,
            'questions': questions,
            'next_page': next_page,
            'current_page': page
        }
        return render(request, self.template_name, context)

    def post(self, request, survey_id, page=1):
        """ Handle user survey answers.

        Make sure that all questions were answered.
        If all are answered then proceed to the next page or to the results page.
        If not, redisplay the page, with the questions marked.

        :param request:
        :param survey_id: numeric
        :param page: numeric
        :return:
        """
        questions_on_page = Question.objects.filter(page__page_num=page, page__survey=survey_id)
        survey = get_object_or_404(Survey, pk=survey_id)
        answered_ids, unanswered_q, answers_so_far = \
            self._process_answers(request=request, questions_on_page=questions_on_page)

        next_page = Page.objects.get_next_page(survey_id, page)

        if len(unanswered_q) == 0:
            request.session['answers'] = answers_so_far
            if next_page:
                # there is another page
                request.session[SurveyView.SURVEY_PAGE] = next_page
                return HttpResponseRedirect(reverse('survey:survey', args=(survey_id, next_page)))

            else:
                # finished the survey
                del request.session[SurveyView.SURVEY_PAGE]
                return HttpResponseRedirect(reverse('survey:result', args=(survey_id,)))
        # some questions were not answered
        # so we're going to redisplay the same page
        context = {
            'unanswered': unanswered_q,
            'answered': answered_ids,
            'survey': survey,
            'next_page': next_page,
            'questions': questions_on_page,
            'current_page': page
        }
        return render(request, self.template_name, context)

    @staticmethod
    def _process_answers(request, questions_on_page):
        unanswered_q = []
        answered_ids = []
        answers_so_far = request.session.get('answers', [])
        for q in questions_on_page:
            answer_ids_str = request.POST.getlist('question[{}]'.format(q.id))
            try:
                answer_ids = map(int, answer_ids_str)
            except ValueError as e:
                answer_ids = []
                unanswered_q.append(q.id)
                logger.info(e)

            if answer_ids:
                answers_so_far += answer_ids
                answered_ids += answer_ids
            else:
                unanswered_q.append(q.id)
        return answered_ids, unanswered_q, answers_so_far


class ResultView(View):
    template_name = 'survey/result.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ResultView, self).dispatch(request, *args, **kwargs)

    def get(self, request, survey_id):
        answer_ids = request.session.get('answers', [])
        score = Answer.objects.get_score_sum(answer_ids)
        request.session['score'] = score

        result = Result.objects.get_result(survey_id, score)
        context = {
            'result': result,
            'score': score,
            'survey_id': survey_id
        }
        logging.debug('score: {}'.format(score))
        return render(request, self.template_name, context)


class ClosestPath(View):
    template_name = 'survey/closest_path.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ClosestPath, self).dispatch(request, *args, **kwargs)

    def get(self, request, survey_id):
        try:
            score = int(request.session.get('score', None))
        except TypeError:
            raise Http404()
        next_result = Result.objects.get_result_above(survey_id, score)
        prev_result = Result.objects.get_result_below(survey_id, score)
        given_ans_ids = request.session.get('answers')

        pages = Page.objects.filter(survey=survey_id)
        other_ans = {}
        given_ans = {}
        # organize the answers by page and question
        # and keep them split into answers the user has submitted
        # and into answers the user has not submitted for that particular page and question
        # this is useful when computing score improvements
        for page in pages:
            answers = Answer.objects.filter(question__page=page).select_related('question')
            given_ans[page.id] = {}
            other_ans[page.id] = {}
            for ans in answers:
                a = AnsTuple(id=ans.id, score=ans.score)
                other_ans[page.id][ans.question_id] = other_ans[page.id].get(ans.question_id, [])
                given_ans[page.id][ans.question_id] = given_ans[page.id].get(ans.question_id, [])

                if ans.id in given_ans_ids:
                    given_ans[page.id][ans.question_id].append(a)
                else:
                    other_ans[page.id][ans.question_id].append(a)

        better, worse = compute_closest_alternatives(score=score,
                                                     next_result=next_result,
                                                     prev_result=prev_result,
                                                     answers=given_ans,
                                                     other_answers=other_ans)
        context = {
            'better': better,
            'worse': worse
        }
        return render(request, self.template_name, context)

survey/templates/survey/base.html
{% extends "main.html" %}
{% load staticfiles %}
{% load site_menu %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'survey/css/survey.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block menu %}
    {% site_menu item=2 %}
{% endblock %}

survey/templates/survey/closest_path.html
<div class="score-alternative">
{% if better %}
    <div>You could have gotten a <b>better</b> result just by doing the following changes to your answers:</div>
    {% for question, answers in better.iteritems %}
        <div class="text-warning">{{question.question_text}}</div>
        {% for ans in answers.add %}
            <div class="indent">[+] {{ans.answer_text}}</div>
        {% endfor %}
        {% for ans in answers.rm %}
            <div class="indent">[-] {{ans.answer_text}}</div>
        {% endfor %}
    {% endfor %}
{% else %}
    No possible changes* for getting a <b>better</b> result. <br>
    * that follow the required rules (1 question change per page)
{% endif %}
</div>
<div class="score-alternative">
{% if worse %}
    <div>You could have gotten a <b>worse</b> result just by doing the following changes to your answers:</div>
    {% for question, answers in worse.iteritems %}
        <div class="text-warning">{{question.question_text}}</div>
        {% for ans in answers.add %}
            <div class="indent">[+] {{ans.answer_text}}</div>
        {% endfor %}
        {% for ans in answers.rm %}
            <div class="indent">[-] {{ans.answer_text}}</div>
        {% endfor %}
    {% endfor %}
{% else %}
    No possible changes* for getting a <b>worse</b> result. <br>
    * that follow the required rules (1 question change per page)
{% endif %}

</div>

survey/templates/survey/list.html
{% extends "survey/base.html" %}
{% block content %}
    <div class="pages">
        {% for page_num in surveys.paginator.page_range %}
            {% if page_num == surveys.number %}
                <span class="page-current">{{page_num}}</span>
            {% else %}
                <a href="{% url 'survey:list' %}?page={{page_num}}">{{page_num}}</a>
            {% endif %}

        {% endfor %}
    </div>

    <ol class="tests-list" start={{start_at}}>
    {% for survey in surveys %}
        <li class="test-item"><a href="{% url 'survey:survey' survey_id=survey.id %}">{{survey.name}}</a><br />
        <div class="description">{{survey.shorten_description}}</div>
        <div class="created-at">{{survey.created_at}}</div>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

survey/templates/survey/result.html
{% extends "survey/base.html" %}
{% load staticfiles%}
{% block content %}
    <h4 class="font-22">Your result:</h4>
    <div class="result bg-info">
        {% if result %}
        <div class="result-summary">{{result.summary}}</div>
            {% if result.description %}
            <div class="result-description">{{result.description}}</div>
            {% endif %}
        {% else %}
        <div>
            It seems that your score does not fit any possible result.
            The person which made the test did something wrong
        </div>
        {% endif %}
    </div>
    <div id="alternative" data-url="{% url 'survey:closest' survey_id%}" data-score="{{score}}">
        <div>
            <div id="loader" class="loader"></div>
        </div>
    </div>
{% endblock %}
{% block asyncjs%}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'survey/js/survey.js' %}"></script>
{% endblock %}

survey/templates/survey/survey.html
{% extends "survey/base.html" %}
{% block content %}
    <div class="survey-title">{{survey.name}}</div>
    <div class="survey-description">{{survey.description}}</div>
    <form action="" method="POST">
        {% csrf_token %}
        {% if unanswered %}
        <p class="bg-danger">You must answer all questions before moving to the next section.</p>
        {% endif %}
        <ul class="survey-page">
        {% for q in questions %}
        <li class="survey-question{% if q.id in unanswered %} text-danger{%endif%}"><span class="question-text">{{q.question_text}}</span>
            <div class="survey-answers">
            {% for ans in q.answer_set.all %}
                <input class="survey-answer" type="{{q.type}}" value="{{ans.id}}"
                       {% if ans.id in answered %}
                            checked="checked"
                       {% endif %}
                       id="answer{{ans.id}}" name="question[{{q.id}}]"/>
                <label for="ans{{ans.id}}">{{ans.answer_text}}</label>
                <br />
            {% endfor %}
            </div>
        </li>
        {% endfor %}
        </ul>
        {% if questions %}
        <button type="submit" class="btn btn-info">
            {% if not next_page %}
                Finish
            {% else %}
                Next
            {% endif %}
        </button>
        {% endif %}
    </form>
{% endblock %}