accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views


urlpatterns = patterns('',
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^create/', views.CreateView.as_view(), name='create')
)

dj_start/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', 'dj_start.views.home', name='home'),
    url(r'^contact/$', include('contact.urls'), name="contact"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^survey/', include('survey.urls', namespace='survey')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
)

survey/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.views import login

from survey import views

survey_patterns = patterns('',
    url(r'^$', views.SurveyView.as_view(), name='survey'),
    url(r'^/page/(?P<page>\d+)$', views.SurveyView.as_view(), name='survey'),
    url(r'^/result$', views.ResultView.as_view(), name='result'),
    url(r'^/closest_path$', views.ClosestPath.as_view(), name='closest')
)

urlpatterns = patterns('',
    url(r'^$', views.ListView.as_view(), name='list'),
    url(r'^(?P<survey_id>\d+)', include(survey_patterns)),
)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms


class NewUserForm(UserCreationForm):
    username = forms.RegexField(
        label="Username",
        max_length=30,
        regex=r'^[\w.]+$',
        help_text="Required. 30 characters or fewer. Letters, digits and "
                      "'.', '_' only.",
        error_messages={
            'invalid': "This value may contain only letters, numbers and "
                         "'.', '_' characters."})

accounts/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth import authenticate, login as login_user
from django.core.urlresolvers import reverse
from accounts.forms import NewUserForm
from django.http.response import HttpResponseRedirect


class LoginView(View):
    template_name = 'accounts/login.html'

    def get(self, request):
        next_link = request.GET.get('next', reverse('survey:list'))
        template_response = login(request=request, template_name=self.template_name)
        template_response.context_data['next'] = next_link
        return template_response

    def post(self, request):
        template_response = login(request=request, template_name=self.template_name)
        return template_response


class LogoutView(View):
    def post(self, request):
        return logout_then_login(request=request)


class CreateView(View):
    template_name = 'accounts/create.html'

    def get(self, request):
        form = NewUserForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            username = form.clean_username()
            password = form.clean_password2()
            form.save()
            user = authenticate(username=username, password=password)
            login_user(request, user)

            return HttpResponseRedirect(reverse('survey:list'))

        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

accounts/templates/accounts/create.html
{% extends "main.html" %}
{% block menu %}
{% endblock %}
{% block content %}

<form class="form-horizontal form-create" role="form" method="post" action="{% url 'accounts:create' %}">
{{ form.non_field_errors }}

{% csrf_token %}
<div class="form-group">
    <label for="username" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-7">
        <input type="text" name="username" class="form-control" id="username" placeholder="Username" value="{{form.data.username}}">
        {% if form.username.errors %}
            <ul>
                {% for err in form.username.errors %}
                    <li class="text-danger">{{ err|escape }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>
<div class="form-group">
    <label for="password1" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-7">
        <input type="password" name="password1" class="form-control" id="password1" placeholder="Password" value="{{form.data.password1}}">
        {% if form.password1.errors %}
            <ul>
                {% for err in form.password1.errors %}
                    <li class="text-danger">{{ err|escape }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>
<div class="form-group">
    <label for="password2" class="col-sm-2 control-label">Password confirmation</label>
    <div class="col-sm-7">
        <input type="password" name="password2" class="form-control" id="password2" placeholder="Confirm password" value="{{form.data.password2}}">
        {% if form.password2.errors %}
            <ul>
                {% for err in form.password2.errors %}
                    <li class="text-danger">{{ err|escape }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-4">
        <button type="submit" class="btn btn-info">Create account</button>
        or
        <a href="{% url 'accounts:login' %}">Login</a>
    </div>
</div>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "main.html" %}
{% block headerlinks %}
{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form class="form-horizontal form-login" role="form" method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<div class="form-group">
    <input type="text" name="username" class="form-control" id="username" placeholder="Username" value="{{form.data.username}}">
</div>
<div class="form-group">
    <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="">
</div>

<div class="form-group">
    <div class="col-sm-offset-4">
        <button type="submit" class="btn btn-default">Sign in</button>
        or
        <a href="{% url 'accounts:create' %}">Create an account</a>
    </div>
</div>
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}